'use client';
import {useState} from 'react';
import {Gift,Sparkles,Heart,ArrowUpLeft} from 'lucide-react';
import {wallet,rewards,tiers} from '@/lib/loyalty.mjs';
export default function Loyalty({data,customer=false,demo=false,onRedeem,onBook}:any){
const [phone,setPhone]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[chosen,setChosen]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
const members=Array.from(new Set<string>(data.bookings.map((b:any)=>b.phone))).map(p=>wallet(data.bookings,data.records,p));
const current=members.find(m=>m.phone===phone)||members[0];
async function confirm(){if(busy)return;setBusy(true);try{await onRedeem({action:'redeem',phone:current.phone,reward:chosen.id,requestId:chosen.requestId});setMessage('تم تسجيل المكافأة وخصم النقاط. تقدم المكافأة في المحل.');setChosen(null)}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
return <div className="loyalty"><section className="loyalty-hero"><div><span className="eyebrow">LUNE CIRCLE · دائرة لون</span><h2>كل زيارة تُزهر.<br/>وكل عناية تعود إليكِ.</h2><p>نقطة لكل ريال في الزيارات المكتملة والمدفوعة. اجمعي نقاطك واختاري لمسة العناية التي تحبينها.</p>{customer&&<button className="outline" onClick={onBook}>ابدئي رحلة العناية <ArrowUpLeft size={16}/></button>}</div><div className="loyalty-orbit"><Sparkles size={40}/><strong>دائرة لون</strong><span>عناية. امتنان. مكافآت.</span></div></section>
<div className="loyalty-tiers">{tiers.map((t:any,i:number)=><article key={t.name}><span>0{i+1} /</span><h3>{t.name}</h3><p>{t.min===0?'تبدأ مع أول زيارة':`${t.min.toLocaleString('ar-SA')} نقطة مكتسبة`}</p><small>{['بداية علاقة تستحق العناية','رحلتك تزهر مع كل زيارة','أعلى مستوى في دائرة لون'][i]}</small></article>)}</div>
{(!customer||demo)&&<><div className="stats three"><div className="stat"><div>عضوات دائرة لون <Heart size={18}/></div><strong>{members.length}</strong></div><div className="stat"><div>نقاط متاحة</div><strong>{members.reduce((n,m)=>n+m.balance,0).toLocaleString('ar-SA')}</strong></div><div className="stat"><div>عميلات يستحققن مكافأة</div><strong>{members.filter(m=>m.balance>=rewards[0].cost).length}</strong></div></div>
{customer?<div className="hint space">محفظة عرض ببيانات وهمية: اختاري عميلة لتجربة ارتباط الولاء بالحجوزات في هذا المتصفح.</div>:<div className="toolbar"><input className="field" aria-label="البحث في عضوات الولاء" placeholder="اسم العميلة أو الجوال" value={query} onChange={e=>setQuery(e.target.value)}/><select className="field" aria-label="تصفية العضوات" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل العضوات</option><option value="ready">يستحققن مكافأة</option><option value="moon">مستوى قمر</option></select></div>}
<label className="form-field"><span>{customer?'اختيار محفظة تجريبية':'محفظة العميلة'}</span><select className="field" value={current?.phone||''} onChange={e=>{setPhone(e.target.value);setChosen(null);setMessage('')}}><option value="" disabled>اختاري عميلة</option>{members.filter(m=>(m.name.includes(query)||m.phone.includes(query))&&(filter==='all'||filter==='ready'&&m.balance>=250||filter==='moon'&&m.tier.name==='قمر')).map(m=><option key={m.phone} value={m.phone}>{m.name} · {m.phone} · {m.balance} نقطة</option>)}</select></label>
{current?<div className="loyalty-wallet"><section className="membership"><span>LUNE CIRCLE <Gift size={20}/></span><h3>{current.name}</h3><small>عضوية {current.tier.name}</small><strong>{current.balance.toLocaleString('ar-SA')} <small>نقطة متاحة</small></strong><div className="loyalty-progress" role="progressbar" aria-label="التقدم إلى المستوى التالي" aria-valuenow={Math.round(current.progress)} aria-valuemin={0} aria-valuemax={100}><i style={{width:current.progress+'%'}}/></div><p>{current.next?`${current.next.min-current.lifetime} نقطة للوصول إلى ${current.next.name}`:'وصلتِ إلى قمر، أعلى مستويات العناية'}</p><small>{current.visits} زيارات مؤهلة · {current.lifetime} نقطة مكتسبة طوال العضوية</small></section><section className="panel service-card"><h3>مسار عنايتك</h3><p>اكتشفي مكافأتك التالية</p>{rewards.map(r=><div className="detail-row" key={r.id}><span>{r.name}</span><b>{current.balance>=r.cost?'متاحة الآن':`${r.cost-current.balance} نقطة متبقية`}</b></div>)}<small>استبدال المكافآت لا يُنقص مستوى عضويتك.</small></section></div>:<div className="empty">تظهر المحفظة بعد أول حجز للعميلة.</div>}</>}
<div className="section-title"><div><span className="eyebrow">LITTLE MOMENTS, BEAUTIFUL REWARDS</span><h2>مكافآت على ذوقك</h2></div></div><div className="cards">{rewards.map((r,i)=><article className="panel service-card reward-card" key={r.id}><div className="service-top"><span className="service-symbol">{['✧','❋','☾'][i]}</span><span className="tag">{r.cost} نقطة</span></div><h3>{r.name}</h3><p>{r.description}</p>{(!customer||demo)&&<button className="outline full" disabled={!current||current.balance<r.cost||busy} onClick={()=>{setChosen({...r,requestId:crypto.randomUUID()});setMessage('')}}>{current&&current.balance>=r.cost?'اختيار المكافأة':'اجمعي نقاطًا أكثر'}</button>}</article>)}</div>
{chosen&&<section className="panel service-card space" role="region" aria-label="تأكيد استبدال المكافأة"><h3>تأكيد {chosen.name}</h3><p>سيتم خصم {chosen.cost} نقطة من محفظة {current.name}. الرصيد بعد الاستبدال: {current.balance-chosen.cost} نقطة. سجّلي الاستبدال عند تقديم المكافأة في المحل.</p><div className="actions"><button className="primary" disabled={busy} onClick={confirm}>{busy?'جارٍ التسجيل...':'تأكيد الاستبدال'}</button><button className="outline" disabled={busy} onClick={()=>setChosen(null)}>رجوع</button></div></section>}{message&&<p className="hint space" role="status">{message}</p>}
{(!customer||demo)&&current&&<section className="panel space"><div className="panel-head"><h2>سجل النقاط</h2><span className="tag">{current.ledger.length} حركة</span></div><div className="loyalty-ledger">{current.ledger.map((r:any)=><div className="detail-row" key={r.id}><span>{r.label}<small>{r.date.slice(0,10)}</small></span><b className={r.points>0?'points-credit':'points-debit'}>{r.points>0?'+':''}{r.points} نقطة</b></div>)}{!current.ledger.length&&<p>تظهر النقاط بعد إكمال الزيارة وتحصيل المبلغ.</p>}</div></section>}
<p className="hint space">تحتسب الزيارات المكتملة والمدفوعة المسجلة في النظام، بما فيها الزيارات السابقة. لا نقاط للحجوزات الملغاة أو عدم الحضور. النقاط لا تنتهي حاليًا ولا تُستبدل نقدًا. المكافآت إضافات عناية يقدمها المحل، وليست خصمًا تلقائيًا من الفاتورة.{customer&&!demo?' للاستعلام عن رصيدك واستبدال مكافآتك تواصلي مع المحل؛ عرض المحفظة الشخصية عن بُعد يحتاج تحققًا من هوية العميلة.':''}</p></div>
}
