import {db} from '@/lib/database';
import {salonTenant,runtime} from '@/lib/access';
import {createBooking,hash} from '@/lib/booking';
import {seed} from '@/lib/seed';
export const dynamic='force-dynamic';
export function publicHeaders(req:Request){const headers=new Headers({'Cache-Control':'no-store','Vary':'Origin','Content-Type':'application/json; charset=utf-8'});const origin=req.headers.get('origin');if(origin&&(origin===new URL(req.url).origin||origin===runtime().PUBLIC_CUSTOMER_ORIGIN)){headers.set('Access-Control-Allow-Origin',origin);headers.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');headers.set('Access-Control-Allow-Headers','Content-Type,Authorization')}return headers}
export function allowedOrigin(req:Request){const origin=req.headers.get('origin');return !origin||origin===new URL(req.url).origin||origin===runtime().PUBLIC_CUSTOMER_ORIGIN}
export function respond(req:Request,data:any,status=200){return Response.json(data,{status,headers:publicHeaders(req)})}
export async function OPTIONS(req:Request){return new Response(null,{status:allowedOrigin(req)?204:403,headers:publicHeaders(req)})}
export async function GET(req:Request){try{const t=salonTenant();await seed(t);const r=await db().prepare("SELECT kind,data FROM records WHERE tenant=? AND kind IN ('service','staff','settings')").bind(t).all();return respond(req,{records:r.results.map((row:any)=>{const d=JSON.parse(row.data);if(row.kind==='staff')return {kind:'staff',id:d.id,name:d.name,title:d.title};return {...d,kind:row.kind}}),bookings:[]})}catch{return respond(req,{error:'تعذر تحميل الخدمات الآن. حاولي مجددًا.'},503)}}
export async function rateLimit(req:Request,scope:string,max:number){const window=Math.floor(Date.now()/60000);const key=scope+':'+await hash(req.headers.get('cf-connecting-ip')||'local');const r=await db().prepare('INSERT INTO request_limits (key,window,hits) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET window=excluded.window,hits=CASE WHEN request_limits.window=excluded.window THEN request_limits.hits+1 ELSE 1 END RETURNING hits').bind(key,window).first<{hits:number}>();return !!r&&r.hits<=max}
export async function POST(req:Request){if(!allowedOrigin(req))return respond(req,{error:'طلب غير مسموح.'},403);if(!req.headers.get('content-type')?.includes('application/json'))return respond(req,{error:'صيغة غير صالحة.'},415);try{const text=await req.text();if(text.length>12000)return respond(req,{error:'حجم الطلب كبير.'},413);let body:any;try{body=JSON.parse(text)}catch{return respond(req,{error:'بيانات غير صالحة.'},400)}if(body?.action!=='book')return respond(req,{error:'العملية غير متاحة.'},403);if(!await rateLimit(req,'book',12))return respond(req,{error:'طلبات كثيرة. انتظري دقيقة وحاولي مجددًا.'},429);const t=salonTenant();await seed(t);const result=await createBooking(t,body,true);return new Response(result.body,{status:result.status,headers:publicHeaders(req)})}catch{return respond(req,{error:'تعذر تأكيد الحجز. حاولي مجددًا.'},500)}}
