import {db} from './database';
import {today} from './catalog';
const json=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function createBooking(t:string,body:any,guest=false){
const {name,phone,date,time,staff:employee,serviceIds}=body;const preferences=body.preferences&&typeof body.preferences==='object'?body.preferences:{};
if(typeof name!=='string'||name.trim().length<2||name.length>100||!/^05\d{8}$/.test(phone)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time)||!Array.isArray(serviceIds)||serviceIds.length<1||serviceIds.length>6||new Set(serviceIds).size!==serviceIds.length)return json({error:'راجعي الاسم ورقم الجوال والخدمات والموعد.'},400);
if(!Number.isFinite(new Date(date+'T'+time+':00+03:00').getTime())||date<today()||date>new Date(Date.now()+180*86400000).toISOString().slice(0,10)||new Date(date+'T'+time+':00+03:00').getTime()<Date.now())return json({error:'اختاري موعدًا قادمًا خلال ١٨٠ يومًا.'},400);
const rr=await db().prepare('SELECT kind,data FROM records WHERE tenant=?').bind(t).all();const records=rr.results.map((r:any)=>({...JSON.parse(r.data),kind:r.kind}));if(!records.find((r:any)=>r.kind==='staff'&&r.id===employee))return json({error:'اختاري أخصائية متاحة.'},400);
const sv=serviceIds.map((id:string)=>records.find((r:any)=>r.kind==='service'&&r.id===id));if(sv.some((s:any)=>!s))return json({error:'الخدمة لم تعد متاحة.'},400);
const duration=sv.reduce((n:number,s:any)=>n+s.duration,0),total=sv.reduce((n:number,s:any)=>n+s.price,0);const minute=Number(time.slice(0,2))*60+Number(time.slice(3));const buffer=15;if(minute<600||minute%15||minute+duration+buffer>1320)return json({error:'المواعيد من ١٠ صباحًا إلى ١٠ مساءً، مع ١٥ دقيقة لتجهيز الغرفة.'},400);
const prefs={quiet:!!preferences.quiet,fragranceFree:!!preferences.fragranceFree,light:preferences.light==='خافتة'?'خافتة':'طبيعية',notes:String(preferences.notes||'').slice(0,500)};const id=crypto.randomUUID();let offset=minute;const claims=new Set<string>();for(const s of sv){for(let m=offset;m<offset+s.duration+buffer;m+=15){claims.add('room:'+s.room+'|'+m);claims.add('staff:'+employee+'|'+m)}offset+=s.duration}
const receipt=guest?crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''):null;
const statements=[db().prepare('INSERT INTO bookings (tenant,id,name,phone,date,time,staff,services,total,duration,status,preferences,paid,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(t,id,name.trim(),phone,date,time,employee,JSON.stringify(sv),total,duration,'confirmed',JSON.stringify(prefs),0,new Date().toISOString()),...Array.from(claims).map(c=>{const split=c.lastIndexOf('|');return db().prepare('INSERT INTO slots (tenant,resource,date,minute,booking) VALUES (?,?,?,?,?)').bind(t,c.slice(0,split),date,Number(c.slice(split+1)),id)})];if(receipt)statements.push(db().prepare('INSERT INTO guest_receipts (token_hash,tenant,booking) VALUES (?,?,?)').bind(await hash(receipt),t,id));try{await db().batch(statements)}catch(e){if(String(e).includes('UNIQUE'))return json({error:'هذا الموعد يتعارض مع حجز الأخصائية أو الغرفة. اختاري وقتًا آخر.'},409);throw e}return json({id,total,status:'confirmed',...(receipt?{receipt}: {})});
}
