import {getChatGPTUser} from '../../chatgpt-auth';
import {db} from '@/lib/database';
import {services,staff,products,today} from '@/lib/catalog';
export const dynamic='force-dynamic';
const json=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
async function identity(){const u=await getChatGPTUser();return u?.userId}
async function seed(t:string){const rows=[...services.map(data=>({kind:'service',data})),...staff.map(data=>({kind:'staff',data})),...products.map(data=>({kind:'product',data})),{kind:'settings',data:{id:'settings',name:'لون سبا',branch:'الرياض · حي الملقا',buffer:15}}];await db().batch(rows.map(r=>db().prepare('INSERT OR IGNORE INTO records (tenant,id,kind,data) VALUES (?,?,?,?)').bind(t,r.data.id,r.kind,JSON.stringify(r.data))))}
export async function GET(){const t=await identity();if(!t)return json({error:'سجّلي الدخول لفتح مساحة العمل.'},401);await seed(t);const [rs,bs]=await Promise.all([db().prepare('SELECT * FROM records WHERE tenant=?').bind(t).all(),db().prepare('SELECT * FROM bookings WHERE tenant=? ORDER BY date DESC,time ASC').bind(t).all()]);return json({records:rs.results.map((r:any)=>({...JSON.parse(r.data),kind:r.kind})),bookings:bs.results.map((b:any)=>({...b,tenant:undefined,services:JSON.parse(b.services),preferences:JSON.parse(b.preferences)}))})}
export async function POST(req:Request){const t=await identity();if(!t)return json({error:'سجّلي الدخول أولًا.'},401);if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'طلب غير مسموح'},403);let body:any;try{body=await req.json()}catch{return json({error:'طلب غير صالح'},400)}
try{if(body.action==='book'){
const {name,phone,date,time,staff:employee,serviceIds,preferences={}}=body;
if(typeof name!=='string'||name.trim().length<2||name.length>100||!/^05\d{8}$/.test(phone)||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time)||!Array.isArray(serviceIds)||serviceIds.length<1||serviceIds.length>6||new Set(serviceIds).size!==serviceIds.length)return json({error:'راجعي الاسم ورقم الجوال والخدمات والموعد.'},400);
if(!Number.isFinite(new Date(date+'T'+time+':00+03:00').getTime())||date<today()||date>new Date(Date.now()+180*86400000).toISOString().slice(0,10)||new Date(date+'T'+time+':00+03:00').getTime()<Date.now())return json({error:'اختاري موعدًا قادمًا خلال ١٨٠ يومًا.'},400);
const rr=await db().prepare('SELECT kind,data FROM records WHERE tenant=?').bind(t).all();const records=rr.results.map((r:any)=>({...JSON.parse(r.data),kind:r.kind}));if(!records.find((r:any)=>r.kind==='staff'&&r.id===employee))return json({error:'اختاري أخصائية متاحة.'},400);
const sv=serviceIds.map((id:string)=>records.find((r:any)=>r.kind==='service'&&r.id===id));if(sv.some((s:any)=>!s))return json({error:'الخدمة لم تعد متاحة.'},400);
const duration=sv.reduce((n:number,s:any)=>n+s.duration,0),total=sv.reduce((n:number,s:any)=>n+s.price,0);const minute=Number(time.slice(0,2))*60+Number(time.slice(3));const buffer=15;if(minute<600||minute%15||minute+duration+buffer>1320)return json({error:'المواعيد من ١٠ صباحًا إلى ١٠ مساءً، مع ١٥ دقيقة لتجهيز الغرفة.'},400);
const prefs={quiet:!!preferences.quiet,fragranceFree:!!preferences.fragranceFree,light:preferences.light==='خافتة'?'خافتة':'طبيعية',notes:String(preferences.notes||'').slice(0,500)};const id=crypto.randomUUID();let offset=minute;const claims=new Set<string>();for(const s of sv){for(let m=offset;m<offset+s.duration+buffer;m+=15){claims.add('room:'+s.room+'|'+m);claims.add('staff:'+employee+'|'+m)}offset+=s.duration}
const statements=[db().prepare('INSERT INTO bookings (tenant,id,name,phone,date,time,staff,services,total,duration,status,preferences,paid,created) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(t,id,name.trim(),phone,date,time,employee,JSON.stringify(sv),total,duration,'confirmed',JSON.stringify(prefs),0,new Date().toISOString()),...Array.from(claims).map(c=>{const split=c.lastIndexOf('|');return db().prepare('INSERT INTO slots (tenant,resource,date,minute,booking) VALUES (?,?,?,?,?)').bind(t,c.slice(0,split),date,Number(c.slice(split+1)),id)})];try{await db().batch(statements)}catch(e){if(String(e).includes('UNIQUE'))return json({error:'هذا الموعد يتعارض مع حجز الأخصائية أو الغرفة. اختاري وقتًا آخر.'},409);throw e}return json({id,total,status:'confirmed'});
}
if(body.action==='status'){
if(!['confirmed','arrived','completed','cancelled','no_show'].includes(body.status))return json({error:'حالة غير صالحة'},400);const b:any=await db().prepare('SELECT * FROM bookings WHERE tenant=? AND id=?').bind(t,body.id).first();if(!b)return json({error:'الحجز غير موجود'},404);if(b.paid>0&&['cancelled','no_show'].includes(body.status))return json({error:'يوجد مبلغ محصّل. عالجي الاسترداد مع المحل قبل إلغاء الحجز.'},409);if(['cancelled','completed','no_show'].includes(b.status))return json({error:'الحجز مغلق ولا يمكن تعديل حالته.'},409);const qs=[db().prepare('UPDATE bookings SET status=? WHERE tenant=? AND id=?').bind(body.status,t,body.id)];if(['cancelled','no_show'].includes(body.status))qs.push(db().prepare('DELETE FROM slots WHERE tenant=? AND booking=?').bind(t,body.id));await db().batch(qs);return json({ok:true})}
if(body.action==='pay'){const r=await db().prepare("UPDATE bookings SET paid=total WHERE tenant=? AND id=? AND status NOT IN ('cancelled','no_show') AND paid=0").bind(t,body.id).run();if(!r.meta.changes)return json({error:'الحجز مدفوع مسبقًا أو ملغي.'},409);return json({ok:true})}
if(body.action==='save'){
const {kind}=body;let d=body.data;if(!d||!['service','staff','product','waitlist','settings','campaign'].includes(kind))return json({error:'بيانات غير صالحة'},400);const id=kind==='settings'?'settings':(typeof d.id==='string'&&d.id.length<100?d.id:crypto.randomUUID());
if(typeof d.name!=='string'||d.name.trim().length<2||d.name.length>100)return json({error:'أدخلي اسمًا صحيحًا.'},400);
if(kind==='service'){if(!Number.isInteger(d.price)||d.price<0||d.price>10000||!Number.isInteger(d.duration)||d.duration<15||d.duration>360||d.duration%15)return json({error:'السعر موجب والمدة مضاعفات ١٥ دقيقة حتى ٣٦٠.'},400);d={id,name:d.name,price:d.price,duration:d.duration,category:String(d.category||'العناية'),room:String(d.room||'غرفة العناية ١'),description:String(d.description||''),icon:'✧'}}
if(kind==='product'){if(!Number.isInteger(d.stock)||d.stock<0||d.stock>100000||!Number.isFinite(d.price)||d.price<0||!Number.isInteger(d.min)||d.min<0)return json({error:'راجعي الكمية والسعر وحد التنبيه.'},400);d={id,name:d.name,stock:d.stock,price:d.price,min:d.min}}
if(kind==='staff')d={id,name:d.name,title:String(d.title||'أخصائية عناية').slice(0,100),commission:Math.max(0,Math.min(100,Number(d.commission)||0)),color:'#eddfeb'};
if(kind==='waitlist'){if(!/^05\d{8}$/.test(d.phone)||!/^\d{4}-\d{2}-\d{2}$/.test(d.date)||d.date<today())return json({error:'راجعي الجوال والتاريخ.'},400);d={id,name:d.name,phone:d.phone,date:d.date,notes:String(d.notes||'').slice(0,300)}}
if(kind==='settings')d={id,name:d.name,branch:String(d.branch||'').slice(0,100),buffer:15};if(kind==='campaign')d={id,name:d.name,text:String(d.text||'').slice(0,2000),status:'draft'};
await db().prepare('INSERT INTO records (tenant,id,kind,data) VALUES (?,?,?,?) ON CONFLICT(tenant,id) DO UPDATE SET data=excluded.data WHERE records.kind=excluded.kind').bind(t,id,kind,JSON.stringify(d)).run();return json({id})}
if(body.action==='removeWaitlist'){await db().prepare("DELETE FROM records WHERE tenant=? AND id=? AND kind='waitlist'").bind(t,body.id).run();return json({ok:true})}
return json({error:'عملية غير معروفة'},400)
}catch(e){console.error('Spa request failed',e);return json({error:'تعذر حفظ التغيير. حاولي مجددًا.'},500)}}
